### ISSUE TITLE
ImportError: No module named 'tzlocal'

### ISSUE THREAD

**Issue by tomswinkels** [dmitryelj/RPi-P2000Receiver#1]
This error i get, how can i fix this?

pi@raspberrypi:~ $ python3 /home/pi/RPi-P2000Receiver/p2000.py
Traceback (most recent call last):
  File "/home/pi/RPi-P2000Receiver/p2000.py", line 23, in <module>
    import libTFT
  File "/home/pi/RPi-P2000Receiver/libTFT.py", line 9, in <module>
    import utils
  File "/home/pi/RPi-P2000Receiver/utils.py", line 3, in <module>
    import tzlocal
ImportError: No module named 'tzlocal'

**Comment by dmitryelj** [comment]
Try: 
sudo pip3 install tzlocal

**Comment by tomswinkels** [comment]
Thnx that works. I also had try:
sudo pip install tzlocal
